mysql:
  secrets:
    MYSQL_ROOT_PASSWORD: placeholder_root_password
    MYSQL_USER: placeholder_mysql_user
    MYSQL_PASSWORD: placeholder_mysql_password

todoapp:
  namespace: todoapp
  image:
    repository: ikulyk404/todoapp
    tag: "4.0.1"

  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  secrets:
    SECRET_KEY: placeholder_secret_key
    DB_NAME: placeholder_db_name
    DB_USER: placeholder_db_user
    DB_PASSWORD: placeholder_db_password
    DB_HOST: placeholder_db_host

  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpu:
      avarageUtilization: 70
    memory:
      avarageUtilization: 70

  volumes:
    persistentVolume:
      capacity: "1Gi"
    persistentVolumeClaim:
      requestStorage: "1Gi"
