mysql:
  secrets:
    MYSQL_ROOT_PASSWORD: placeholder-for-mysql-root-password
    MYSQL_USER: placeholder-for-mysql-user
    MYSQL_PASSWORD: placeholder-for-mysql-password

todoapp:
  namespace: todoapp
  image:
    repository: ikulyk404/todoapp
    tag: "4.0.1"

  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  secrets:
    SECRET_KEY: placeholder-for-secret-key
    DB_NAME: placeholder-for-db-name
    DB_USER: placeholder-for-db-user
    DB_PASSWORD: placeholder-for-db-password
    DB_HOST: placeholder-for-db-host

  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpu:
      avarageUtilization: 70
    memory:
      avarageUtilization: 70

  volumes:
    persistentVolume:
      capacity: "1Gi"
    persistentVolumeClaim:
      requestStorage: "1Gi"
