name: python-deployment

run-name: ${{ github.actor }} - ${{ github.ref_name}} -${{ github.sha }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      artefact-to-deploy:
        description: "Select artefact to deploy"
        required: true
        type: choice
        options:
          - "ubuntu-3.9"
          - "ubuntu-3.10"
          - "windows-3.9"
          - "windows-3.10"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.9
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/todoapp

jobs:
  python-ci:
    name: Python CI
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - artefact: ubuntu-3.9
            os: ubuntu-latest
            python-version: "3.9"
          - artefact: ubuntu-3.10
            os: ubuntu-latest
            python-version: "3.10"
          - artefact: windows-3.9
            os: windows-latest
            python-version: "3.9"
          - artefact: windows-3.10
            os: windows-latest
            python-version: "3.10"

    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            src/requirements.txt
            src/requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Tests with Coverage
        run: |
          coverage run --source='.' manage.py test
          coverage report

      - name: Linting
        run: |
          flake8 . --show-source --statistics --exit-zero

      - name: Check Complexity
        run: |
          flake8 . --exit-zero --max-complexity=10

      - name: Upload python artifact
        if: matrix.artefact == github.event.inputs.artefact-to-deploy
        uses: actions/upload-artifact@v4
        with:
          name: python-artifacts-${{ matrix.artefact }}
          path: src/*

      - name: Upload Helm Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: helm-artifacts
          path: ${{ github.workspace }}/helm-charts/*

  docker-ci:
    name: Docker CI
    needs: python-ci
    uses: ./.github/workflows/docker-ci.yml
    with:
      os-type: ${{ contains(github.event.inputs.artefact-to-deploy, 'windows') && 'windows-latest' || 'ubuntu-latest' }}
      python-artifact: python-artifacts-${{ github.event.inputs.artefact-to-deploy }}

  helm-ci:
    name: Helm CI
    runs-on: ubuntu-latest
    needs: python-ci

    steps:
      - name: Download Helm Artifacts
        uses: actions/download-artifact@v4
        with:
          name: helm-artifacts
          path: ./helm-charts

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Lint Helm Charts
        run: helm lint helm-charts/todoapp

      - name: Template Helm Charts
        run: helm template todoapp helm-charts/todoapp -f helm-charts/todoapp/values.yaml

      - name: Package Helm Charts
        run: helm package helm-charts/todoapp --destination helm-charts/packages

      - name: Upload Packaged Helm Charts
        uses: actions/upload-artifact@v4
        with:
          name: helm-packaged-artifacts
          path: helm-charts/packages/*.tgz

  deploy-helm-dev:
    name: Deployment
    needs: [helm-ci, docker-ci]
    uses: ./.github/workflows/reusable-deployment.yml
    secrets: inherit
    with:
      environment: development
      docker-image-version: "${{ github.sha }}"

  deploy-helm-stg:
    name: Deployment
    needs: [deploy-helm-dev]
    uses: ./.github/workflows/reusable-deployment.yml
    secrets: inherit
    with:
      environment: staging
      docker-image-version: "${{ github.sha }}"
      helm-values-path: "./helm-charts/todoapp/values/stg.yaml"
