name: Helm Deploy
run-name: Deploy to ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        description: "Target environment for deployment"
        required: true
        type: string
      docker-image-version:
        description: "Docker image version to deploy"
        required: true
        type: string
      helm-values-path:
        description: "Path to Helm values file"
        required: false
        type: string
        default: "./helm-charts/todoapp/values.yaml"
      cluster-config-path:
        description: "Path to kind cluster config file"
        required: false
        type: string
        default: "cluster.yml"

env:
  HELM_RELEASE_NAME: todoapp
  KIND_CLUSTER_NAME: todoapp-cluster
  CHART_PKG_PATH: ./helm-charts/packages
  DOCKER_IMAGE_NAME: todoapp

jobs:
  deploy-helm:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Packaged Helm Charts
        uses: actions/download-artifact@v4
        with:
          name: helm-packaged-artifacts
          path: ${{ env.CHART_PKG_PATH }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          config: ${{ inputs.cluster-config-path }}
          cluster_name: ${{ env.KIND_CLUSTER_NAME }}

      - name: Dry-run Helm install
        run: |
          helm install --dry-run ${{ env.HELM_RELEASE_NAME }} \
            ${{ env.CHART_PKG_PATH }}/todoapp-*.tgz

      - name: Deploy Helm Chart
        env:
          DOCKER_IMAGE_REPO: "${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}"
        run: |
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} \
            ${{ env.CHART_PKG_PATH }}/todoapp-*.tgz \
            --namespace ${{ inputs.environment }} \
            --create-namespace \
            --atomic \
            --wait \
            --timeout 300s \
            -f ${{ inputs.helm-values-path }} \
            --set todoapp.secrets.SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            --set todoapp.secrets.DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            --set todoapp.secrets.DB_USER="${{ secrets.DB_USER }}" \
            --set todoapp.secrets.DB_NAME="${{ secrets.DB_NAME }}" \
            --set todoapp.secrets.DB_HOST="${{ secrets.DB_HOST }}" \
            --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
            --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
            --set mysql.secrets.MYSQL_USER="${{ secrets.DB_USER }}" \
            --set todoapp.image.repository="${{ env.DOCKER_IMAGE_REPO }}" \
            --set todoapp.image.tag="${{ inputs.docker-image-version }}"
